name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set your desired Node version

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # This will generate the build folder

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.1
      with:
        branch: gh-pages  # The branch where the site will be deployed
        folder: build  # The folder to deploy (this should be your build directory)

